name: greenlinkapp
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/GreenLinkLogo.png
