name: greenlinkapp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  geocoding: ^4.0.0
  geolocator: ^13.0.1
  shared_preferences: ^2.5.4
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  riverpod_annotation: ^3.0.3
  image_picker: ^1.2.1
  image: ^4.2.0
  elegant_notification: ^2.5.1
  logger: ^2.6.2
  webview_flutter: ^4.9.0
  socket_io_client: ^3.1.3
  qr_flutter: ^4.1.0
  open_file: ^3.5.11
  pdf: ^3.11.3
  timezone: ^0.11.0
  path_provider: ^2.1.5
  mobile_scanner: ^7.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/GreenLinkLogo.png

# se modfifichi usa dinuovo flutter pub run flutter_native_splash:create per rigenerare le icone
flutter_native_splash:
  color: "#ffffff"
  image: assets/GreenLinkLogo.png
  android_gravity: center
  ios_content_mode: scaleAspectFit

# se modifichi esegui flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/GreenLinkLogo.png"
  min_sdk_android: 21

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/GreenLinkLogo.png"
